[package]
name = "tests"
version = "0.2.0"
edition = "2021"

[dev-dependencies]
casper-types.workspace = true
casper-engine-test-support = { git = "https://github.com/casper-network/casper-node.git", branch = "feat-2.0", default-features = false }
casper-execution-engine = { git = "https://github.com/casper-network/casper-node.git", branch = "feat-2.0", default-features = false }

[[bin]]
name = "integration-tests"
path = "src/integration_tests.rs"
bench = false
doctest = false
