[package]
name = "contract"
version = "0.2.0"
authors = ["darthsiroftardis <karan@casperlabs.io>"]
edition = "2018"

[dependencies]
casper-types.workspace = true
casper-contract = { git = "https://github.com/casper-network/casper-node", branch = "feat-2.0" }

[[bin]]
name = "contract"
path = "src/main.rs"
bench = false
doctest = false
test = false
